
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: teamcity-deploy
  name: teamcity-deploy
  namespace: kube-system


apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: teamcity-deploy
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

#apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: RoleBinding
#metadata:
#  name: teamcity-deploy-binding
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: teamcity-deploy
#subjects:
#- kind: User
#  name: teamcity-deploy
